@TaskManager_HostAddress = http://localhost:5199

GET {{TaskManager_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TaskManager_HostAddress}}/weatherforecast

###

POST {{TaskManager_HostAddress}}/api/auth/Register
Content-Type: application/json

{
  //RegisterDto
}

###
